

# 通用错误 [1-100]
EC_LOGIN_INVALID = 1
ER_LOGIN_INVALID = "请先进行登录"

# 注册错误 [100-200]

EC_REGISTER_PHONENUM_TYPE_ERROR = 101
ER_REGISTER_PHONENUM_TYPE_ERROR = "手机号格式错误，请重新输入"

EC_REGISTER_PHONENUM_REPEAT_ERROR = 102
ER_REGISTER_PHONENUM_REPEAT_ERROR = "手机号重复，请重新输入"

EC_REGISTER_ID_CARD_TYPE_ERROR = 103
ER_REGISTER_ID_CARD_TYPE_ERROR = "身份证格式错误，请重新输入"

EC_REGISTER_PWD_TYPE_ERROR = 104
ER_REGISTER_PWD_TYPE_ERROR = "密码格式错误，请重新输入"

# 登录错误 [201-300]
EC_LOGIN_USERID_ERROR = 201
ER_LOGIN_USERID_ERROR = "账号不存在，请重新输入"
EC_LOGIN_PASSWORD_ERROR = 202
ER_LOGIN_PASSWORD_ERROR = "密码错误，请重新输入"
EC_LOGIN_STATUS_ERROR = 203
ER_LOGIN_STATUS_ERROR = "账号被冻结了"
EC_LOGIN_HANDLE_ERROR = 204
ER_LOGIN_HANDLE_ERROR = "登录处理失败"

# 商城错误 [301-400]
EC_SHOP_BUY_SHOPVERSION_LOW = 301
ER_SHOP_BUY_SHOPVERSION_LOW = "商城版本号过低，请重试"
EC_SHOP_BUY_PROPID_NOT_IN_SHOPLIST = 302
ER_SHOP_BUY_PROPID_NOT_IN_SHOPLIST = "该商品未上架"
EC_SHOP_BUY_PROPID_NOT_EXIST = 303
ER_SHOP_BUY_PROPID_NOT_EXIST = "该商品不存在"
EC_SHOP_BUY_CLIENTVERSION_LOW = 304
ER_SHOP_BUY_CLIENTVERSION_LOW = "客户端版本号过低，请重试"
EC_SHOP_BUY_INVENTORY_NOT_ENOUGH = 305
ER_SHOP_BUY_INVENTORY_NOT_ENOUGH = "库存不足"
EC_SHOP_BUY_MONEY_NOTENOUGH = 306
ER_SHOP_BUY_MONEY_NOTENOUGH = "游戏币不足，请充值后重新购买"


# 任务错误[401-500]
EC_TASK_ID_INVALID = 401
ER_TASK_ID_INVALID = "任务ID无效，请重新输入"
EC_TASK_NOT_FINISTH = 402
ER_TASK_NOT_FINISTH = "用户尚未完成该任务"
EC_TASK_SIGN_TYPE_ERROR = 403
ER_TASK_SIGN_TYPE_ERROR = "签到类型错误"




